# Generated by Django 6.0.3 on 2026-03-25 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cedula de ciudadanía'), ('TI', 'Tarjeta de identidad'), ('CE', 'Cedula de extranjería'), ('PP', 'Pasaporte')], max_length=2),
        ),
    ]
