# Generated by Django 6.0.3 on 2026-03-24 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_automatico', models.BooleanField(default=False, verbose_name='Backup automático activo')),
                ('frecuencia_horas', models.PositiveIntegerField(default=24, verbose_name='Frecuencia (horas)')),
                ('max_backups', models.PositiveIntegerField(default=10, verbose_name='Máximo de backups a conservar')),
                ('incluir_media', models.BooleanField(default=True, verbose_name='Incluir archivos media')),
                ('ruta_backups', models.CharField(blank=True, default='', help_text='Dejar vacío para usar la ruta por defecto (backups/)', max_length=500, verbose_name='Ruta personalizada')),
                ('ultimo_backup', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Configuración de Backup',
                'verbose_name_plural': 'Configuración de Backups',
            },
        ),
        migrations.CreateModel(
            name='BackupRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del backup')),
                ('tipo', models.CharField(choices=[('completo', 'Completo (BD + Media)'), ('base_datos', 'Solo Base de Datos'), ('media', 'Solo Archivos Media')], default='completo', max_length=20)),
                ('estado', models.CharField(choices=[('exitoso', 'Exitoso'), ('fallido', 'Fallido'), ('en_progreso', 'En Progreso'), ('restaurado', 'Restaurado')], default='en_progreso', max_length=20)),
                ('archivo', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ruta del archivo')),
                ('tamano', models.BigIntegerField(default=0, verbose_name='Tamaño en bytes')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('notas', models.TextField(blank=True, default='', verbose_name='Notas / Observaciones')),
                ('es_automatico', models.BooleanField(default=False, verbose_name='¿Backup automático?')),
                ('tablas_incluidas', models.TextField(blank=True, default='', help_text='Lista de tablas incluidas en el backup (separadas por coma).', verbose_name='Tablas incluidas')),
                ('duracion_segundos', models.FloatField(default=0, verbose_name='Duración (seg)')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backups_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Backup',
                'verbose_name_plural': 'Backups',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
