# Generated by Django 6.0.3 on 2026-04-07 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0003_backup_architecture_contracts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupconfig',
            name='permitir_restore_cross_engine',
            field=models.BooleanField(default=False, help_text='No habilita restauracion operativa directa entre motores distintos; solo reserva el modulo para flujos de migracion/importacion controlados.', verbose_name='Habilitar migracion asistida entre motores'),
        ),
        migrations.AlterField(
            model_name='backuprecord',
            name='ultima_accion',
            field=models.CharField(choices=[('creado', 'Creado'), ('importado', 'Importado'), ('restaurado', 'Restaurado'), ('backup_seguridad', 'Backup previo a restaurar'), ('fallido', 'Fallido'), ('fallido_creacion', 'Fallo al crear'), ('fallido_restauracion', 'Fallo al restaurar'), ('fallido_importacion', 'Fallo al importar')], default='creado', max_length=20, verbose_name='Ultima accion'),
        ),
    ]
