# Generated by Django 6.0.3 on 2026-03-27 00:19

from django.db import migrations, models


def normalizar_stock_negativo(apps, schema_editor):
    Stock = apps.get_model("inventario", "Stock")
    Stock.objects.filter(cantidad_actual__lt=0).update(cantidad_actual=0)


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0003_alter_producto_descripcion_alter_producto_linea_and_more'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(normalizar_stock_negativo, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad_actual__gte', 0)), name='inventario_stock_cantidad_no_negativa'),
        ),
    ]
