# Generated by Django 6.0.3 on 2026-03-26 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_alter_personal_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='correo',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='personal',
            name='telefono',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='personal',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('PAS', 'Pasaporte'), ('PEP', 'Permiso Especial de Permanencia'), ('PPT', 'Permiso por Protección Temporal')], default='CC', max_length=5),
        ),
    ]
