# Generated by Django 6.0.3 on 2026-03-26 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_alter_personal_correo_alter_personal_telefono_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='correo',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='personal',
            name='telefono',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='personal',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('PAS', 'Pasaporte'), ('NIT', 'NIT')], default='CC', max_length=5),
        ),
    ]
