# Generated by Django 6.0.3 on 2026-03-26 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_alter_personal_correo_alter_personal_telefono_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='rol',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Auxiliar', 'Auxiliar'), ('Colaborador', 'Colaborador')], default='Colaborador', max_length=20),
        ),
    ]
