BACKUP_TYPE_DB = "base_datos"
BACKUP_TYPE_MEDIA = "media"
BACKUP_TYPE_FULL = "completo"

BACKUP_TYPES = (
    BACKUP_TYPE_FULL,
    BACKUP_TYPE_DB,
    BACKUP_TYPE_MEDIA,
)

BACKUP_STATUS_SUCCESS = "exitoso"
BACKUP_STATUS_FAILED = "fallido"
BACKUP_STATUS_IN_PROGRESS = "en_progreso"
BACKUP_STATUS_RESTORED = "restaurado"

BACKUP_STATUSES = (
    BACKUP_STATUS_SUCCESS,
    BACKUP_STATUS_FAILED,
    BACKUP_STATUS_IN_PROGRESS,
    BACKUP_STATUS_RESTORED,
)

BACKUP_META_FILENAME = "backup_meta.json"
BACKUP_DB_FILENAME = "db.sqlite3"
BACKUP_FORMAT_VERSION = 1

