BACKUP_TYPE_DB = "base_datos"
BACKUP_TYPE_MEDIA = "media"
BACKUP_TYPE_FULL = "completo"

BACKUP_TYPES = (
    BACKUP_TYPE_FULL,
    BACKUP_TYPE_DB,
    BACKUP_TYPE_MEDIA,
)

BACKUP_STATUS_SUCCESS = "exitoso"
BACKUP_STATUS_FAILED = "fallido"
BACKUP_STATUS_IN_PROGRESS = "en_progreso"
BACKUP_STATUS_RESTORED = "restaurado"

BACKUP_STATUSES = (
    BACKUP_STATUS_SUCCESS,
    BACKUP_STATUS_FAILED,
    BACKUP_STATUS_IN_PROGRESS,
    BACKUP_STATUS_RESTORED,
)

BACKUP_META_FILENAME = "backup_meta.json"
BACKUP_DB_FILENAME = "db.sqlite3"
BACKUP_FORMAT_VERSION = 1
BACKUP_DEFAULT_RESTORE_MODE = "overwrite"

BACKUP_ACTION_CREATED = "creado"
BACKUP_ACTION_IMPORTED = "importado"
BACKUP_ACTION_RESTORED = "restaurado"
BACKUP_ACTION_SECURITY = "backup_seguridad"
BACKUP_ACTION_FAILED = "fallido"
BACKUP_ACTION_FAILED_CREATE = "fallido_creacion"
BACKUP_ACTION_FAILED_RESTORE = "fallido_restauracion"
BACKUP_ACTION_FAILED_IMPORT = "fallido_importacion"

BACKUP_ACTIONS = (
    BACKUP_ACTION_CREATED,
    BACKUP_ACTION_IMPORTED,
    BACKUP_ACTION_RESTORED,
    BACKUP_ACTION_SECURITY,
    BACKUP_ACTION_FAILED,
    BACKUP_ACTION_FAILED_CREATE,
    BACKUP_ACTION_FAILED_RESTORE,
    BACKUP_ACTION_FAILED_IMPORT,
)

DB_ENGINE_SQLITE = "sqlite"
DB_ENGINE_POSTGRES = "postgresql"
DB_ENGINES = (
    DB_ENGINE_SQLITE,
    DB_ENGINE_POSTGRES,
)

RESTORE_MODE_OVERWRITE = "overwrite"
RESTORE_MODE_MIRROR = "mirror"
RESTORE_MODES = (
    RESTORE_MODE_OVERWRITE,
    RESTORE_MODE_MIRROR,
)
