# Generated by Django 6.0.3 on 2026-03-31 03:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_tipo_documento'),
        ('gestion_alisados', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TabletConsentToken',
            fields=[
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('expira_en', models.DateTimeField()),
                ('usado_en', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tablet_consent_tokens', to='clientes.cliente', verbose_name='Cliente')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tablet_consent_tokens_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('gestion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tablet_tokens', to='gestion_alisados.gestionalisado', verbose_name='Gestión relacionada')),
            ],
            options={
                'verbose_name': 'Token de tablet',
                'verbose_name_plural': 'Tokens de tablet',
                'ordering': ['-creado_en'],
            },
        ),
    ]
