# Generated by Django 6.0.3 on 2026-04-07 01:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_ciudad_cliente_direccion_and_more'),
        ('gestion_alisados', '0005_tabletkioskstate_realtime_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AtencionServicio',
            fields=[
                ('id_atencion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_atencion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de la atencion')),
                ('sede', models.CharField(blank=True, default='', max_length=150, verbose_name='Sede')),
                ('profesional_o_asesor', models.CharField(max_length=200, verbose_name='Profesional o asesor')),
                ('tipo_servicio', models.CharField(max_length=200, verbose_name='Tipo de servicio')),
                ('estado_atencion', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='Estado de la atencion')),
                ('observaciones_atencion', models.TextField(blank=True, default='', verbose_name='Observaciones de la atencion')),
                ('tratamiento_completado', models.BooleanField(default=False, verbose_name='Tratamiento completado')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atenciones_servicio', to='clientes.cliente', verbose_name='Cliente relacionado')),
                ('usuario_registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atenciones_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que registro')),
            ],
            options={
                'verbose_name': 'Atencion o servicio',
                'verbose_name_plural': 'Atenciones o servicios',
                'ordering': ['-fecha_atencion'],
            },
        ),
        migrations.AddField(
            model_name='gestionalisado',
            name='atencion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gestion_alisado_detalle', to='gestion_alisados.atencionservicio', verbose_name='Atencion relacionada'),
        ),
        migrations.CreateModel(
            name='TratamientoDatosFirmado',
            fields=[
                ('id_tratamiento', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_hora_firma', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de firma')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviada_a_tablet', 'Enviada a tablet'), ('abierta_en_tablet', 'Abierta en tablet'), ('firmada', 'Firmada'), ('cancelada', 'Cancelada'), ('expirada', 'Expirada'), ('error', 'Error')], db_index=True, default='pendiente', max_length=30, verbose_name='Estado')),
                ('texto_tratamiento', models.TextField(verbose_name='Texto exacto del tratamiento firmado')),
                ('version_tratamiento', models.CharField(default='v1', max_length=50, verbose_name='Version del tratamiento')),
                ('ruta_archivo_firma', models.CharField(blank=True, default='', max_length=255, verbose_name='Ruta del archivo de la firma')),
                ('hash_integridad', models.CharField(blank=True, default='', max_length=128, verbose_name='Hash de integridad')),
                ('sede', models.CharField(blank=True, default='', max_length=150, verbose_name='Sede')),
                ('tablet_utilizada', models.CharField(blank=True, default='', max_length=120, verbose_name='Tablet utilizada')),
                ('snapshot_cliente', models.JSONField(default=dict, verbose_name='Snapshot de datos del cliente')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('atencion', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='tratamiento_datos', to='gestion_alisados.atencionservicio', verbose_name='Atencion o servicio relacionado')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tratamientos_datos', to='clientes.cliente', verbose_name='Cliente relacionado')),
                ('usuario_cierre_proceso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tratamientos_cerrados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que cerro el proceso')),
                ('usuario_inicio_proceso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tratamientos_iniciados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que inicio el proceso')),
            ],
            options={
                'verbose_name': 'Tratamiento de datos firmado',
                'verbose_name_plural': 'Tratamientos de datos firmados',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.AddField(
            model_name='gestionalisado',
            name='tratamiento_firmado',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gestion_alisado_detalle', to='gestion_alisados.tratamientodatosfirmado', verbose_name='Tratamiento firmado relacionado'),
        ),
    ]
