# Generated by Django 6.0.3 on 2026-03-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=100)),
                ('nombre', models.CharField(help_text='Nombre del producto', max_length=60, unique=True, verbose_name='Nombre del Producto')),
                ('precio', models.IntegerField(help_text='Precio del producto en pesos colombianos', verbose_name='Precio')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('linea', models.CharField(blank=True, max_length=45, verbose_name='Línea')),
                ('presentacion', models.CharField(blank=True, max_length=50, verbose_name='Presentación')),
                ('unidad_medida', models.CharField(choices=[('unidad', 'Unidad'), ('kg', 'Kilogramo'), ('g', 'Gramo'), ('litro', 'Litro'), ('ml', 'Mililitro'), ('caja', 'Caja'), ('paquete', 'Paquete'), ('metro', 'Metro')], default='unidad', max_length=45, verbose_name='Unidad de Medida')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('imagen_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['nombre'], name='Productos_p_nombre_3c70d2_idx'), models.Index(fields=['linea'], name='Productos_p_linea_c2718c_idx')],
            },
        ),
    ]
