# Generated by Django 6.0.3 on 2026-03-25 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0002_alter_producto_unidad_medida_remove_imagen_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='linea',
            field=models.CharField(blank=True, max_length=45, verbose_name='Linea'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='presentacion',
            field=models.CharField(blank=True, max_length=50, verbose_name='Presentacion'),
        ),
    ]
