# Generated by Django 6.0.3 on 2026-03-24 14:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la Promoción')),
                ('descripcion', models.TextField(blank=True, help_text='Texto que se muestra en la tarjeta pública', verbose_name='Descripción')),
                ('etiqueta', models.CharField(choices=[('nuevo', 'Nuevo'), ('especial', 'Especial'), ('limitado', 'Limitado'), ('descuento', 'Descuento'), ('exclusivo', 'Exclusivo')], default='nuevo', help_text='Badge visible en la web pública', max_length=20, verbose_name='Etiqueta')),
                ('porcentaje_descuento', models.DecimalField(decimal_places=2, help_text='Valor entre 0 y 100', max_digits=5, verbose_name='% de Descuento')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Fin')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='promociones/', verbose_name='Imagen')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
            ],
            options={
                'verbose_name': 'Promoción',
                'verbose_name_plural': 'Promociones',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
