# Generated by Django 6.0.3 on 2026-04-07 22:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0002_compra_compras_compra_precio_total_no_negativo_and_more'),
        ('gestion_alisados', '0006_atencionservicio_gestionalisado_atencion_and_more'),
        ('personal', '0005_alter_personal_rol'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaFinanciera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('tipo', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('BANCO', 'Banco'), ('BILLETERA', 'Billetera'), ('OTRA', 'Otra')], default='EFECTIVO', max_length=20)),
                ('activa', models.BooleanField(default=True)),
                ('orden_visual', models.PositiveIntegerField(default=0)),
                ('color', models.CharField(blank=True, default='', max_length=20)),
                ('icono', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'verbose_name': 'Cuenta financiera',
                'verbose_name_plural': 'Cuentas financieras',
                'ordering': ['orden_visual', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='JornadaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA_AUTO', 'Cerrada automáticamente')], default='ABIERTA', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre_auto', models.DateTimeField(blank=True, null=True)),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jornadas_financieras_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Jornada diaria',
                'verbose_name_plural': 'Jornadas diarias',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida')], max_length=10)),
                ('clase', models.CharField(choices=[('SERVICIO', 'Servicio'), ('COMPRA', 'Compra'), ('AJUSTE', 'Ajuste'), ('TRANSFERENCIA', 'Transferencia'), ('ANULACION', 'Anulación'), ('REVERSA', 'Reversa')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=0, max_digits=18)),
                ('concepto', models.CharField(max_length=255)),
                ('referencia', models.CharField(blank=True, default='', max_length=120)),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('ANULADO', 'Anulado')], default='ACTIVO', max_length=10)),
                ('request_uid', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('colaborador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_financieros', to='personal.personal')),
                ('compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_financieros', to='compras.compra')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='control_fondos.cuentafinanciera')),
                ('jornada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='control_fondos.jornadadiaria')),
                ('movimiento_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_reversa', to='control_fondos.movimientocuenta')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_financieros', to='gestion_alisados.gestionalisado')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_financieros_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de cuenta',
                'verbose_name_plural': 'Movimientos de cuenta',
                'ordering': ['-fecha_hora', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TransferenciaCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=0, max_digits=18)),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('cuenta_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_entrantes', to='control_fondos.cuentafinanciera')),
                ('cuenta_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_salientes', to='control_fondos.cuentafinanciera')),
                ('movimiento_entrada', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='transferencia_entrada', to='control_fondos.movimientocuenta')),
                ('movimiento_salida', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='transferencia_salida', to='control_fondos.movimientocuenta')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_financieras_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transferencia entre cuentas',
                'verbose_name_plural': 'Transferencias entre cuentas',
                'ordering': ['-fecha_hora', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BaseDiariaCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_inicial', models.DecimalField(decimal_places=0, max_digits=18)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('observacion', models.TextField(blank=True, default='')),
                ('registrada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bases_financieras_registradas', to=settings.AUTH_USER_MODEL)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bases_diarias', to='control_fondos.cuentafinanciera')),
                ('jornada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bases_cuenta', to='control_fondos.jornadadiaria')),
            ],
            options={
                'verbose_name': 'Base diaria por cuenta',
                'verbose_name_plural': 'Bases diarias por cuenta',
                'ordering': ['jornada__fecha', 'cuenta__orden_visual', 'cuenta__nombre'],
                'constraints': [models.UniqueConstraint(fields=('jornada', 'cuenta'), name='control_fondos_base_diaria_cuenta_unica_por_jornada'), models.CheckConstraint(condition=models.Q(('base_inicial__gte', 0)), name='control_fondos_base_diaria_base_inicial_no_negativa')],
            },
        ),
        migrations.AddConstraint(
            model_name='movimientocuenta',
            constraint=models.CheckConstraint(condition=models.Q(('valor__gt', 0)), name='control_fondos_movimiento_cuenta_valor_mayor_cero'),
        ),
        migrations.AddConstraint(
            model_name='movimientocuenta',
            constraint=models.UniqueConstraint(condition=models.Q(('request_uid__isnull', False)), fields=('request_uid',), name='control_fondos_movimiento_cuenta_request_uid_unico'),
        ),
        migrations.AddConstraint(
            model_name='transferenciacuenta',
            constraint=models.CheckConstraint(condition=models.Q(('valor__gt', 0)), name='control_fondos_transferencia_valor_mayor_cero'),
        ),
        migrations.AddConstraint(
            model_name='transferenciacuenta',
            constraint=models.CheckConstraint(condition=models.Q(('cuenta_origen', models.F('cuenta_destino')), _negated=True), name='control_fondos_transferencia_cuentas_distintas'),
        ),
    ]
