# Generated by Django 6.0.3 on 2026-05-08 00:24

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def _normalize(value):
    value = (value or "").strip().lower()
    return " ".join(value.split())


def forwards_standardize_cuentas(apps, schema_editor):
    CuentaFinanciera = apps.get_model("control_fondos", "CuentaFinanciera")
    BaseDiariaCuenta = apps.get_model("control_fondos", "BaseDiariaCuenta")

    cuentas = list(CuentaFinanciera.objects.all().order_by("id"))

    def _save(cuenta, nombre, codigo, tipo):
        cuenta.nombre = nombre
        cuenta.codigo = codigo
        cuenta.nombre_normalizado = _normalize(nombre)
        cuenta.tipo = tipo
        cuenta.activa = False
        cuenta.save(update_fields=["nombre", "codigo", "nombre_normalizado", "tipo", "activa"])

    banco_candidates = [c for c in cuentas if _normalize(c.nombre) in {"bancolombia", "bancolombiaa"}]
    bank_keep = None
    for candidate in banco_candidates:
        if BaseDiariaCuenta.objects.filter(cuenta_id=candidate.id).exists():
            bank_keep = candidate
            break
    if bank_keep is None and banco_candidates:
        bank_keep = banco_candidates[0]
    if bank_keep:
        _save(bank_keep, "Bancolombia", "BANCOLOMBIA", "BANCO")
        for candidate in banco_candidates:
            if candidate.id != bank_keep.id and not BaseDiariaCuenta.objects.filter(cuenta_id=candidate.id).exists():
                candidate.delete()

    caja_principal_std = next((c for c in cuentas if c.nombre == "Caja Principal"), None)
    if caja_principal_std is None:
        caja_principal_std = next((c for c in cuentas if _normalize(c.nombre) == "caja principal" and BaseDiariaCuenta.objects.filter(cuenta_id=c.id).exists()), None)
    if caja_principal_std is None:
        caja_principal_std = next((c for c in cuentas if _normalize(c.nombre) == "caja principal"), None)
    if caja_principal_std:
        _save(caja_principal_std, "Caja Principal", "CAJA_PRINCIPAL", "EFECTIVO")

    caja_fuerte = next(
        (
            c
            for c in cuentas
            if _normalize(c.nombre) == "caja principal"
            and c.id != (caja_principal_std.id if caja_principal_std else -1)
            and not BaseDiariaCuenta.objects.filter(cuenta_id=c.id).exists()
        ),
        None,
    )
    if caja_fuerte:
        _save(caja_fuerte, "Caja Fuerte", "CAJA_FUERTE", "CAJA_FUERTE")

    standard_accounts = [
        ("CAJA_PRINCIPAL", "Caja Principal", "EFECTIVO", 1),
        ("CAJA_FUERTE", "Caja Fuerte", "CAJA_FUERTE", 2),
        ("BANCOLOMBIA", "Bancolombia", "BANCO", 3),
        ("NEQUI", "Nequi", "BILLETERA", 4),
        ("DAVIPLATA", "Daviplata", "BILLETERA", 5),
        ("NU_BANK", "Nu Bank", "BANCO", 6),
        ("DATAFONO", "Datáfono", "DATAFONO", 7),
        ("SISTECREDITO_ADDI", "Sistecrédito / Addi", "FINANCIACION", 8),
        ("TARJETA_CREDITO_COMPRAS", "Tarjeta Crédito Compras", "TARJETA", 9),
    ]
    existing_codes = set(CuentaFinanciera.objects.values_list("codigo", flat=True))
    for codigo, nombre, tipo, orden in standard_accounts:
        cuenta = CuentaFinanciera.objects.filter(codigo=codigo).first()
        if cuenta is None:
            cuenta = CuentaFinanciera.objects.filter(nombre_normalizado=_normalize(nombre)).first()
        if cuenta is None:
            cuenta = CuentaFinanciera.objects.create(
                codigo=codigo,
                nombre=nombre,
                nombre_normalizado=_normalize(nombre),
                tipo=tipo,
                activa=False,
                orden_visual=orden,
            )
            existing_codes.add(codigo)
            continue
        cuenta.codigo = codigo
        cuenta.nombre = nombre
        cuenta.nombre_normalizado = _normalize(nombre)
        cuenta.tipo = tipo
        cuenta.activa = False
        cuenta.orden_visual = orden
        cuenta.save(update_fields=["codigo", "nombre", "nombre_normalizado", "tipo", "activa", "orden_visual"])
        existing_codes.add(codigo)

    for cuenta in CuentaFinanciera.objects.all():
        if not cuenta.codigo and cuenta.nombre:
            cuenta.codigo = cuenta.nombre_normalizado.upper().replace(" ", "_")
            cuenta.save(update_fields=["codigo"])


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_compra_cuenta_financiera'),
        ('control_fondos', '0001_initial'),
        ('gestion_alisados', '0006_atencionservicio_gestionalisado_atencion_and_more'),
        ('personal', '0005_alter_personal_rol'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BitacoraFondos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=60)),
                ('modelo', models.CharField(blank=True, default='', max_length=80)),
                ('objeto_id', models.CharField(blank=True, default='', max_length=80)),
                ('datos_anteriores', models.JSONField(blank=True, default=dict)),
                ('datos_nuevos', models.JSONField(blank=True, default=dict)),
                ('motivo', models.TextField(blank=True, default='')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('dispositivo', models.CharField(blank=True, default='', max_length=180)),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Bitácora de fondos',
                'verbose_name_plural': 'Bitácora de fondos',
                'ordering': ['-fecha_hora', '-id'],
            },
        ),
        migrations.RemoveField(
            model_name='jornadadiaria',
            name='creada_por',
        ),
        migrations.RemoveField(
            model_name='jornadadiaria',
            name='fecha_cierre_auto',
        ),
        migrations.AddField(
            model_name='cuentafinanciera',
            name='codigo',
            field=models.CharField(blank=True, db_index=True, max_length=60, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cuentafinanciera',
            name='nombre_normalizado',
            field=models.CharField(db_index=True, default='', editable=False, max_length=160),
        ),
        migrations.AddField(
            model_name='jornadadiaria',
            name='autorizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jornadas_financieras_autorizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jornadadiaria',
            name='base_inicial_caja',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='jornadadiaria',
            name='base_inicial_caja_fuerte',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='jornadadiaria',
            name='caja_fuerte_contada_real',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='jornadadiaria',
            name='datofono_verificado',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='jornadadiaria',
            name='diferencia_caja',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='jornadadiaria',
            name='diferencia_caja_fuerte',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='jornadadiaria',
            name='diferencia_datofono',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='jornadadiaria',
            name='diferencia_financiacion',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='jornadadiaria',
            name='diferencia_transferencias',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='jornadadiaria',
            name='efectivo_contado_real',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='jornadadiaria',
            name='fecha_cierre',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jornadadiaria',
            name='fecha_reapertura',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jornadadiaria',
            name='financiacion_verificada',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='jornadadiaria',
            name='motivo_reapertura',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jornadadiaria',
            name='observacion_apertura',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jornadadiaria',
            name='observacion_cierre',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jornadadiaria',
            name='responsable_apertura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jornadas_financieras_abiertas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jornadadiaria',
            name='sede',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='jornadadiaria',
            name='transferencias_verificadas',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='jornadadiaria',
            name='usuario_cierre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jornadas_financieras_cerradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimientocuenta',
            name='concepto',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='movimientocuenta',
            name='bancolombia',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='movimientocuenta',
            name='cliente',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AddField(
            model_name='movimientocuenta',
            name='comprobante',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='movimientocuenta',
            name='datofono',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='movimientocuenta',
            name='daviplata',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='movimientocuenta',
            name='descuento',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='movimientocuenta',
            name='entrada_efectivo',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='movimientocuenta',
            name='estado_validacion',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('ANULADO', 'Anulado'), ('CORREGIDO', 'Corregido'), ('PENDIENTE_VALIDACION', 'Pendiente de validación'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE_VALIDACION', max_length=30),
        ),
        migrations.AddField(
            model_name='movimientocuenta',
            name='fecha_validacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimientocuenta',
            name='ingreso_caja_fuerte',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='movimientocuenta',
            name='motivo_salida',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AddField(
            model_name='movimientocuenta',
            name='nequi',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='movimientocuenta',
            name='nubank',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='movimientocuenta',
            name='observacion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='movimientocuenta',
            name='procedimiento',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AddField(
            model_name='movimientocuenta',
            name='producto_servicio',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AddField(
            model_name='movimientocuenta',
            name='profesional',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AddField(
            model_name='movimientocuenta',
            name='retiro_caja_fuerte',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='movimientocuenta',
            name='salida_efectivo',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='movimientocuenta',
            name='sistecredito_addi',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='movimientocuenta',
            name='tarjeta_credito_compras',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='movimientocuenta',
            name='tipo_movimiento',
            field=models.CharField(blank=True, choices=[('INGRESO', 'Ingreso'), ('SALIDA', 'Salida'), ('TRANSFERENCIA_INTERNA', 'Transferencia interna'), ('AJUSTE', 'Ajuste'), ('ANULACION', 'Anulación'), ('COMPRA_TARJETA', 'Compra con tarjeta')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='movimientocuenta',
            name='usuario_validacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_financieros_validados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimientocuenta',
            name='valor_neto',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='movimientocuenta',
            name='valor_total',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='transferenciacuenta',
            name='comprobante',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='transferenciacuenta',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='APROBADA', max_length=20),
        ),
        migrations.AddField(
            model_name='transferenciacuenta',
            name='fecha_validacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transferenciacuenta',
            name='observacion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='transferenciacuenta',
            name='referencia',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='transferenciacuenta',
            name='usuario_validacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_financieras_validadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cuentafinanciera',
            name='nombre',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='cuentafinanciera',
            name='tipo',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('BANCO', 'Banco'), ('BILLETERA', 'Billetera'), ('CAJA_FUERTE', 'Caja fuerte'), ('DATAFONO', 'Datáfono'), ('FINANCIACION', 'Financiación'), ('TARJETA', 'Tarjeta'), ('OTRA', 'Otra')], default='EFECTIVO', max_length=20),
        ),
        migrations.AlterField(
            model_name='jornadadiaria',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE_APERTURA', 'Pendiente de apertura'), ('ABIERTO', 'Abierto'), ('EN_REVISION', 'En revisión'), ('CERRADO', 'Cerrado'), ('REABIERTO_CON_AUTORIZACION', 'Reabierto con autorización'), ('CERRADO_AUTO', 'Cerrado automáticamente')], default='PENDIENTE_APERTURA', max_length=30),
        ),
        migrations.AlterField(
            model_name='movimientocuenta',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('ANULADO', 'Anulado'), ('CORREGIDO', 'Corregido'), ('PENDIENTE_VALIDACION', 'Pendiente de validación'), ('RECHAZADO', 'Rechazado')], default='ACTIVO', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='cuentafinanciera',
            constraint=models.UniqueConstraint(condition=models.Q(('nombre_normalizado', ''), _negated=True), fields=('nombre_normalizado',), name='control_fondos_cuenta_nombre_normalizado_unico'),
        ),
        migrations.AddConstraint(
            model_name='movimientocuenta',
            constraint=models.CheckConstraint(condition=models.Q(('valor_total__gte', 0)), name='control_fondos_movimiento_cuenta_valor_total_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='movimientocuenta',
            constraint=models.CheckConstraint(condition=models.Q(('descuento__gte', 0)), name='control_fondos_movimiento_cuenta_descuento_no_negativo'),
        ),
        migrations.AddField(
            model_name='bitacorafondos',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacoras_control_fondos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(forwards_standardize_cuentas, migrations.RunPython.noop),
    ]
