# Generated by Django 6.0.3 on 2026-05-08 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_fondos', '0003_cuenta_financiera_operacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jornadadiaria',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE_APERTURA', 'Pendiente de apertura'), ('APERTURA_INCOMPLETA', 'Apertura incompleta'), ('ABIERTO', 'Abierto'), ('EN_REVISION', 'En revisión'), ('CERRADO', 'Cerrado'), ('REABIERTO_CON_AUTORIZACION', 'Reabierto con autorización'), ('CERRADO_AUTO', 'Cerrado automáticamente')], default='PENDIENTE_APERTURA', max_length=30),
        ),
    ]
