# Generated by Django 6.0.3 on 2026-05-08 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_fondos', '0004_alter_jornadadiaria_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocuenta',
            name='soporte_adjunto',
            field=models.FileField(blank=True, null=True, upload_to='control_fondos/soportes/movimientos/'),
        ),
        migrations.AddField(
            model_name='transferenciacuenta',
            name='soporte_adjunto',
            field=models.FileField(blank=True, null=True, upload_to='control_fondos/soportes/transferencias/'),
        ),
    ]
