"""
Django settings for MONAPP project.

Generated by 'django-admin startproject' using Django 5.2.1.
"""

from pathlib import Path
import os
import importlib.util
import sys
from django.core.exceptions import ImproperlyConfigured
from decouple import Csv, config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY", default="django-insecure-change-me")
# SECURITY WARNING: don't run with debug turned on in production!
# Acepta valores comunes: true/false/1/0/on/off/yes/no y también "release"/"prod" => False.
_debug_raw = str(config("DEBUG", default="True")).strip().lower()
if _debug_raw in {"release", "prod", "production"}:
    DEBUG = False
else:
    DEBUG = _debug_raw in {"1", "true", "yes", "y", "on", "debug"}

if not DEBUG and SECRET_KEY == "django-insecure-change-me":
    raise ImproperlyConfigured("SECRET_KEY debe configurarse en produccion.")

ALLOWED_HOSTS = config("ALLOWED_HOSTS", default="localhost,127.0.0.1,192.168.1.44,192.168.1.21", cast=Csv())
CSRF_TRUSTED_ORIGINS = config("CSRF_TRUSTED_ORIGINS", default="", cast=Csv())
if not DEBUG and not ALLOWED_HOSTS:
    raise ImproperlyConfigured("ALLOWED_HOSTS debe configurarse en produccion.")

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'core',
    'backup',
    'clientes',
    'usuarios.apps.UsuariosConfig',
    'Productos.apps.ProductosConfig',
    'Proveedores',
    'ventas.apps.VentasConfig',
    'personal',
    'inventario',
    'gestion_alisados',
    'control_fondos.apps.ControlFondosConfig',
    'productos_web',
    'compras.apps.ComprasConfig',
    'django_bootstrap5',  
    'promociones',
    'servicios_web',
    'servicios.apps.ServiciosConfig',
    'notificaciones',
]

CHANNELS_INSTALLED = importlib.util.find_spec("channels") is not None
CHANNELS_REDIS_INSTALLED = importlib.util.find_spec("channels_redis") is not None
RUNNING_TESTS = "test" in sys.argv
ENABLE_CHANNELS = config(
    "ENABLE_CHANNELS",
    default=(CHANNELS_INSTALLED if (DEBUG or RUNNING_TESTS) else True),
    cast=bool,
)

if ENABLE_CHANNELS and CHANNELS_INSTALLED:
    INSTALLED_APPS.append('channels')

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'core.middleware.SecurityHeadersMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'core.middleware.RolePermissionMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.Pretty404Middleware',
]

ROOT_URLCONF = 'MONAPP.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.permisos_usuario',
                'usuarios.context_processors.login_security',
            ],
        },
    },
]

WSGI_APPLICATION = 'MONAPP.wsgi.application'
ASGI_APPLICATION = 'MONAPP.asgi.application'

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Internationalization
LANGUAGE_CODE = 'es-co'
TIME_ZONE = 'America/Bogota'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/' 
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (Imágenes subidas)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CONFIGURACIÓN DE EMAIL (SMTP GMAIL)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = config("EMAIL_HOST_USER", default="monappadso@gmail.com")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD", default="")
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# URLs de redirección
LOGIN_URL = 'core:index'
LOGIN_REDIRECT_URL = 'core:dashboard'
LOGOUT_REDIRECT_URL = 'core:index'

# Login endurecido
LOGIN_RECAPTCHA_SITE_KEY = config("RECAPTCHA_SITE_KEY", default="")
LOGIN_RECAPTCHA_SECRET_KEY = config("RECAPTCHA_SECRET_KEY", default="")
LOGIN_SECURITY_FORCE_CAPTCHA = config("LOGIN_SECURITY_FORCE_CAPTCHA", default=True, cast=bool)
LOGIN_TRUSTED_PROXY_IPS = config("LOGIN_TRUSTED_PROXY_IPS", default="", cast=Csv())
if not DEBUG and LOGIN_SECURITY_FORCE_CAPTCHA and (not LOGIN_RECAPTCHA_SITE_KEY or not LOGIN_RECAPTCHA_SECRET_KEY):
    raise ImproperlyConfigured("RECAPTCHA_SITE_KEY y RECAPTCHA_SECRET_KEY son obligatorios en produccion.")

# Configuración de sesiones
SESSION_COOKIE_AGE = 28800  # 8 horas
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# Seguridad extra en producción (HTTPS recomendado)
# Por defecto queda desactivada para que el login funcione en localhost/http.
USE_STRICT_HTTPS_SECURITY = config("USE_STRICT_HTTPS_SECURITY", default=False, cast=bool)
SESSION_COOKIE_SECURE = config("SESSION_COOKIE_SECURE", default=USE_STRICT_HTTPS_SECURITY, cast=bool)
CSRF_COOKIE_SECURE = config("CSRF_COOKIE_SECURE", default=USE_STRICT_HTTPS_SECURITY, cast=bool)
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = False
SESSION_COOKIE_SAMESITE = config("SESSION_COOKIE_SAMESITE", default="Lax")
CSRF_COOKIE_SAMESITE = config("CSRF_COOKIE_SAMESITE", default="Lax")

SECURE_SSL_REDIRECT = config("SECURE_SSL_REDIRECT", default=USE_STRICT_HTTPS_SECURITY, cast=bool)
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"
X_FRAME_OPTIONS = "DENY"
SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin"
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

SECURE_HSTS_SECONDS = config("SECURE_HSTS_SECONDS", default=(31536000 if USE_STRICT_HTTPS_SECURITY else 0), cast=int)
SECURE_HSTS_INCLUDE_SUBDOMAINS = config("SECURE_HSTS_INCLUDE_SUBDOMAINS", default=USE_STRICT_HTTPS_SECURITY, cast=bool)
SECURE_HSTS_PRELOAD = config("SECURE_HSTS_PRELOAD", default=USE_STRICT_HTTPS_SECURITY, cast=bool)

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 8},
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

CHANNEL_LAYER_BACKEND = config(
    "CHANNEL_LAYER_BACKEND",
    default=("memory" if DEBUG else "redis"),
).strip().lower()
CHANNEL_REDIS_URL = config("CHANNEL_REDIS_URL", default="redis://127.0.0.1:6379/1")

if ENABLE_CHANNELS and CHANNELS_INSTALLED:
    if not DEBUG and not RUNNING_TESTS and CHANNEL_LAYER_BACKEND != "redis":
        raise ImproperlyConfigured(
            "En produccion, CHANNEL_LAYER_BACKEND debe ser 'redis' para Channels."
        )
    if not DEBUG and not RUNNING_TESTS and CHANNEL_LAYER_BACKEND == "redis" and not CHANNELS_REDIS_INSTALLED:
        raise ImproperlyConfigured(
            "En produccion, Channels requiere channels_redis instalado y Redis disponible."
        )
    if CHANNEL_LAYER_BACKEND == "redis" and CHANNELS_REDIS_INSTALLED:
        CHANNEL_LAYERS = {
            "default": {
                "BACKEND": "channels_redis.core.RedisChannelLayer",
                "CONFIG": {
                    "hosts": [CHANNEL_REDIS_URL],
                },
            }
        }
    else:
        CHANNEL_LAYERS = {
            "default": {
                "BACKEND": "channels.layers.InMemoryChannelLayer",
            }
        }
elif ENABLE_CHANNELS and not CHANNELS_INSTALLED and not DEBUG and not RUNNING_TESTS:
    raise ImproperlyConfigured(
        "ENABLE_CHANNELS esta activo pero el paquete 'channels' no esta instalado."
    )

# Nota: evita hardcodear contraseñas/secretos en el repositorio.
