# Generated by Django 6.0.3 on 2026-03-24 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(blank=True, choices=[('tarjeta_identidad', 'Tarjeta de Identidad'), ('cedula', 'Cédula'), ('pasaporte', 'Pasaporte'), ('otro', 'Otro')], default='cedula', help_text='Tipo de documento de identidad', max_length=30, null=True)),
                ('documento', models.CharField(blank=True, help_text='Número de documento de identidad', max_length=20, null=True, unique=True)),
                ('telefono', models.CharField(blank=True, help_text='Número de teléfono', max_length=15)),
                ('direccion', models.CharField(blank=True, help_text='Dirección de residencia', max_length=200)),
                ('foto_perfil', models.ImageField(blank=True, help_text='Foto de perfil del usuario', null=True, upload_to='perfiles/')),
                ('fecha_nacimiento', models.DateField(blank=True, help_text='Fecha de nacimiento', null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('recovery_code', models.CharField(blank=True, help_text='Código de recuperación de contraseña', max_length=6, null=True)),
                ('recovery_code_created', models.DateTimeField(blank=True, help_text='Fecha de creación del código de recuperación', null=True)),
                ('whatsapp_key', models.CharField(blank=True, help_text='API Key de CallMeBot para recibir alertas por WhatsApp', max_length=20, null=True, verbose_name='CallMeBot API Key')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
                'ordering': ['-user__date_joined'],
            },
        ),
    ]
