# Generated by Django 6.0.3 on 2026-03-24 14:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioWeb',
            fields=[
                ('id_servicio_web', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Servicio')),
                ('descripcion', models.TextField(verbose_name='Descripción del Servicio')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio al público')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='servicios_web/imagenes/', verbose_name='Imagen del Servicio (opcional)')),
                ('video', models.FileField(blank=True, null=True, upload_to='servicios_web/videos/', verbose_name='Video del Servicio (opcional)')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('servicio_origen', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicio_web', to='servicios.servicio', verbose_name='Servicio origen')),
            ],
            options={
                'verbose_name': 'Servicio Web',
                'verbose_name_plural': 'Servicios Web',
                'ordering': ['nombre'],
            },
        ),
    ]
