# Generated by Django 6.0.3 on 2026-03-24 14:10

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoWeb',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Producto')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01, message='El precio debe ser mayor a $0.'), django.core.validators.MaxValueValidator(9999999.99, message='El precio no puede superar $9,999,999.99.')], verbose_name='Precio Público')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos_web/', verbose_name='Imagen')),
                ('visible', models.BooleanField(default=True, verbose_name='Visible en la Web')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
            ],
            options={
                'verbose_name': 'Catálogo Web',
                'verbose_name_plural': 'Catálogos Web',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
