# Generated by Django 6.0.3 on 2026-03-27 00:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0003_alter_producto_descripcion_alter_producto_linea_and_more'),
        ('Proveedores', '0001_initial'),
        ('compras', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='compra',
            constraint=models.CheckConstraint(condition=models.Q(('precio_total__gte', 0)), name='compras_compra_precio_total_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='detallecompra',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='compras_detallecompra_cantidad_mayor_cero'),
        ),
        migrations.AddConstraint(
            model_name='detallecompra',
            constraint=models.CheckConstraint(condition=models.Q(('precio_unitario__gt', 0)), name='compras_detallecompra_precio_unitario_mayor_cero'),
        ),
        migrations.AddConstraint(
            model_name='detalledevolucioncompra',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='compras_detalledevolucioncompra_cantidad_mayor_cero'),
        ),
        migrations.AddConstraint(
            model_name='detalledevolucioncompra',
            constraint=models.CheckConstraint(condition=models.Q(('precio_unitario__gt', 0)), name='compras_detalledevolucioncompra_precio_unitario_mayor_cero'),
        ),
        migrations.AddConstraint(
            model_name='devolucioncompra',
            constraint=models.CheckConstraint(condition=models.Q(('total__gte', 0)), name='compras_devolucioncompra_total_no_negativo'),
        ),
    ]
