# Generated by Django 6.0.3 on 2026-04-07 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_compra_compras_compra_precio_total_no_negativo_and_more'),
        ('control_fondos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='cuenta_financiera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='control_fondos.cuentafinanciera'),
        ),
    ]
