# Generated by Django 6.0.3 on 2026-03-31 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_tipo_documento'),
        ('gestion_alisados', '0002_tabletconsenttoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabletKioskState',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('waiting', 'En espera'), ('ready', 'Proceso listo')], default='waiting', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tablet_kiosk_states', to='clientes.cliente', verbose_name='Cliente')),
                ('gestion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tablet_kiosk_states', to='gestion_alisados.gestionalisado', verbose_name='Gestión')),
                ('token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kiosk_states', to='gestion_alisados.tabletconsenttoken', verbose_name='Token activo')),
            ],
            options={
                'verbose_name': 'Estado de kiosco tablet',
                'verbose_name_plural': 'Estado de kiosco tablet',
            },
        ),
    ]
