# Generated by Django 6.0.3 on 2026-03-30 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthSecurityState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_type', models.CharField(choices=[('user', 'Usuario'), ('ip', 'IP')], db_index=True, max_length=10)),
                ('subject_value', models.CharField(db_index=True, max_length=150)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('block_level', models.PositiveSmallIntegerField(default=0)),
                ('blocked_until', models.DateTimeField(blank=True, null=True)),
                ('strong_block_until', models.DateTimeField(blank=True, null=True)),
                ('captcha_required_until', models.DateTimeField(blank=True, null=True)),
                ('suspicious_until', models.DateTimeField(blank=True, null=True)),
                ('reputation_score', models.PositiveIntegerField(default=0)),
                ('reputation_expires_at', models.DateTimeField(blank=True, null=True)),
                ('burst_count', models.PositiveIntegerField(default=0)),
                ('burst_strikes', models.PositiveIntegerField(default=0)),
                ('burst_window_started_at', models.DateTimeField(blank=True, null=True)),
                ('burst_block_until', models.DateTimeField(blank=True, null=True)),
                ('last_burst_at', models.DateTimeField(blank=True, null=True)),
                ('last_failed_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estado de seguridad',
                'verbose_name_plural': 'Estados de seguridad',
                'indexes': [models.Index(fields=['subject_type', 'subject_value'], name='usuarios_au_subject_68ae33_idx'), models.Index(fields=['blocked_until'], name='usuarios_au_blocked_cea354_idx'), models.Index(fields=['strong_block_until'], name='usuarios_au_strong__8dcd3e_idx'), models.Index(fields=['suspicious_until'], name='usuarios_au_suspici_6dde1e_idx')],
                'unique_together': {('subject_type', 'subject_value')},
            },
        ),
        migrations.CreateModel(
            name='AuthSecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('login_success', 'Login exitoso'), ('login_failed', 'Login fallido'), ('login_blocked', 'Login bloqueado'), ('captcha_required', 'Captcha requerido'), ('captcha_failed', 'Captcha fallido'), ('logout', 'Cierre de sesión'), ('recovery_requested', 'Recuperación solicitada'), ('recovery_code_sent', 'Código de recuperación enviado'), ('recovery_code_failed', 'Código de recuperación fallido'), ('recovery_code_verified', 'Código de recuperación verificado'), ('password_changed', 'Contraseña cambiada'), ('username_recovery', 'Recuperación de usuario')], db_index=True, max_length=32)),
                ('subject_type', models.CharField(blank=True, choices=[('user', 'Usuario'), ('ip', 'IP')], default='', max_length=10)),
                ('subject_value', models.CharField(blank=True, default='', max_length=150)),
                ('username', models.CharField(blank=True, default='', max_length=150)),
                ('ip_address', models.CharField(db_index=True, max_length=45)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('success', models.BooleanField(default=False)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento de seguridad',
                'verbose_name_plural': 'Eventos de seguridad',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='usuarios_au_event_t_97054e_idx'), models.Index(fields=['ip_address', 'created_at'], name='usuarios_au_ip_addr_c32d44_idx'), models.Index(fields=['username', 'created_at'], name='usuarios_au_usernam_a777ba_idx')],
            },
        ),
    ]
