# Generated by Django 6.0.3 on 2026-03-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=20, unique=True, verbose_name='NIT')),
                ('nombre_proveedor', models.CharField(max_length=150, unique=True, verbose_name='Proveedor')),
                ('telefono_proveedor', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('correo_proveedor', models.EmailField(max_length=254, verbose_name='Correo')),
                ('direccion_proveedor', models.CharField(max_length=200, verbose_name='Dirección')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre_proveedor'],
                'indexes': [models.Index(fields=['nombre_proveedor'], name='Proveedores_nombre__d083d7_idx'), models.Index(fields=['nit'], name='Proveedores_nit_cf99e8_idx'), models.Index(fields=['estado'], name='Proveedores_estado_b8ba9d_idx')],
            },
        ),
    ]
